[app]
GOOGLE_API_KEY = "AlzaSyC5gg9s544YmQ9axNf2wPVj2XgqhslCKP0"
MONGODB_URI = "mongodb+srv://dpkevin835_dbd_user:U57wXzaP8mL15GZS@cluster-kadp.nrhexa5.mongodb.net/?appName=Cluster-KADP"
USER = "Kevin Alexander Durand Pizarro"
COHERE_API_KEY = "VUCPicrTOOndei35UECixoCs6f0y43nkSEz9wcvt"

[b2]
B2_BUCKET_NAME = "bucket-KADP"
B2_READ_KEY_ID = "005d0438f819f3d0000000003"
B2_READ_APPLICATION_KEY = "K005nCkb1/Q4xYm+tlOSHLRdtmVhrkk"
B2_WRITE_KEY_ID = "005d0438f819f3d0000000004"
B2_WRITE_APPLICATION_KEY = "K0055CYTKBLN4y2Fd/sMmvr=Hz51Zvl"
